defaults:
  - base

dataset:
  name: metr-la
  scenario: point
  scale_window_factor: 1
  batch_size: 16
  
# Model hyperparameters:
model_config:
  undersampling_factor_time: 1
  undersampling_factor_node: 9

epochs: 300

missing_pattern:
  strategy1: point
  strategy2: null
