defaults:
  - base

dataset:
  name: aqi-36
  scenario: point
  scale_window_factor: 1
  batch_size: 16

# Model hyperparameters:
model_config:
  undersampling_factor_time: 2
  undersampling_factor_node: 2

missing_pattern:
  strategy1: point
  strategy2: historical

weight_name: version_3/epoch=199-val_loss=43.89074.ckpt
