# Scheduler hyperparameters:
curriculum_kwargs:
    s0: 10
    s1: 200

timestep_generator_kwargs:
    p_mean: -1.1
    p_std: 2.0

scheduler_kwargs:
    sigma_min: 0.002
    sigma_max: 80.0
    sigma_data: 0.5
    rho: 7.0

model_config:
    channels: 64
    nem_blocks: 4
    dropout: 0.2
    n_heads: 8
    

seed: 42
epochs: 300
n_experiments: 5
optimizer_type: 1
accelerator: 'gpu'

model_name: "ctimba"


weights:
  # Path to the pretrained weights
  path: ../../weights/${model_name}_${dataset.name}_${dataset.scenario}/${weight_name}

hydra:
  run:
    dir: ./results/impute_${model_name}_${dataset.name}_${dataset.scenario}_x${dataset.scale_window_factor}/